Repository RedHatInsights/edge-frontend, pull requests merged in 2022-09, with the labels that each got.

#535 Restore non-API SearchInput component for RemoveDeviceModal
  src/Routes/Devices/AddDeviceModal.js
  src/Routes/Devices/RemoveDeviceModal.js
  src/components/SearchInput.js
  src/components/SearchInputApi.js
Labels: bug fix, ready

#537 Fix table sorting after modal submit
  src/Routes/Devices/Inventory.js
  src/Routes/Groups/GroupTable.js
  src/Routes/Groups/Groups.js
  src/Routes/ImageManager/ImageSetsTable.js
  src/Routes/ImageManager/Images.js
  src/Routes/Repositories/Repositories.js
  src/components/general-table/GeneralTable.js
Labels: bug fix, ready

#542 Fix table sorting after modal submit for custom repositories
  src/Routes/Repositories/RepositoryTable.js
Labels: bug fix, ready

#543 THEEDGE-2573
  cypress/e2e/groups/CreateGroupModal.cy.js
  cypress/support/commands.js
Labels: bug fix, new feature

#544 Include API error msg in notification dispatched by apiWithToast
  src/utils/apiWithToast.js
Labels: bug fix, ready

#547 THEEDGE-2575 - [UI] Add test to cover RenameGroupModal.js
  cypress/e2e/groups/RenameGroupModal.cy.js
  cypress/e2e/repositories/EditModal.cy.js
  cypress/e2e/repositories/RemoveModal.cy.js
Labels: documentation, bug fix, new feature

#548 THEEDGE-2589 Added new status and retry popover on device details
  src/App.scss
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/Devices/DeviceTable.js
  src/Routes/Devices/RetryUpdatePopover.js
  src/components/Status.js
Labels: new feature

#552 Cypress tests for Retry Popover with Unresponsive and Error status'
  cypress/e2e/systems/RetryUpdate.cy.js
Labels: test update

#553 Fix unresponsive message and uppercase
  src/Routes/Devices/RetryUpdatePopover.js
Labels: bug fix

#551 Fix breadcrumbs in GroupsDetail
  src/Routes/GroupsDetail/GroupsDetail.js
Labels: bug fix, ready

#550 Remove invalid hasIcon prop from HelperText components
  src/Routes/Repositories/modals/EditModal.js
  src/components/form/ImageOutputCheckbox.js
Labels: bug fix, ready

#549 THEEDGE-2574
  cypress/e2e/groups/DeleteGroupModal.cy.js
  cypress/fixtures/contents.json
Labels: new feature, test update

#546 SearchInputApi fixes
  src/components/SearchInputApi.js
Labels: bug fix, ready

#554 Add new code owners
  .github/CODEOWNERS
Labels: new feature

#557 RetryUpdatePopover fixes
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/Devices/DeviceTable.js
  src/Routes/Devices/RetryUpdatePopover.js
Labels: bug fix, ready

#555 THEEDGE-2487
  src/Routes/GroupsDetail/GroupsDetail.js
  src/Routes/ImageManagerDetail/DetailsHeader.js
  src/Routes/ImageManagerDetail/__snapshots__/DetailsHeader.test.js.snap
  src/components/general-table/ToolbarKebab.js
Labels: bug fix, ready

#534 Add update button to inventory
  cypress/e2e/systems/UpdateSystemsWizard.cy.js
  cypress/fixtures/getImageSet.json
  cypress/fixtures/systemTable.json
  src/Routes/Devices/DeviceTable.js
  src/Routes/Devices/Inventory.js
  src/Routes/Devices/UpdateDeviceModal.js
  src/components/general-table/ToolbarHeader.js
Labels: new feature

#559 Fixed device update button inconsistency
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/DeviceDetail/Vulnerability.js
  src/Routes/Devices/DeviceTable.js
Labels: bug fix
