Repository RedHatInsights/edge-frontend, pull requests merged in 2022-12, with the labels that each got.

#612 THEEDGE-2466 - Breadcrumbs aren't correct when going from groups to devices
  src/Routes.js
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/DeviceDetail/Vulnerability.js
  src/Routes/Devices/DeviceTable.js
  src/constants/routeMapper.js
Labels: documentation, bug fix, ready, new feature

#614 Move update system page to a new route
  src/Routes.js
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/Devices/DeviceTable.js
  src/Routes/Devices/Inventory.js
  src/Routes/Devices/UpdateSystem.js
  src/Routes/Devices/UpdateVersionTable.js
  src/Routes/Groups/GroupTable.js
  src/Routes/GroupsDetail/GroupsDetail.js
  src/api/devices/index.js
  src/components/DeviceDetail.js
  src/constants/routeMapper.js
Labels: bug fix, ready

#616 Remove unused query params from getImageSetView
  src/api/images/index.js
Labels: bug fix, ready

#618 redirecting to new update page from Actions dropdown
  src/Routes.js
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/Devices/UpdateSystem.js
  src/components/general-table/ToolbarFooter.js
  src/components/general-table/__snapshots__/ToolbarFooter.test.js.snap
  src/constants/routeMapper.js
Labels: documentation, bug fix, ready

#620 THEEDGE-2922 reloading data after update from image details page
  src/Routes/ImageManagerDetail/ImageDetail.js
Labels: bug fix, ready, test update

#619 THEEDGE-2929
  src/App.js
  src/Routes.js
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/Devices/DeviceTable.js
  src/Routes/Devices/Inventory.js
  src/Routes/Devices/UpdateSystem.js
  src/Routes/Devices/UpdateVersionTable.js
  src/Routes/Groups/GroupTable.js
  src/Routes/Groups/Groups.js
  src/Routes/Groups/__snapshots__/Groups.test.js.snap
  src/Routes/GroupsDetail/GroupsDetail.js
  src/Routes/ImageManager/ImageSetsTable.js
  src/Routes/ImageManager/ImageTable.js
  src/Routes/ImageManager/Images.js
  src/Routes/ImageManagerDetail/DetailsHeader.js
  src/Routes/ImageManagerDetail/ImageDetail.js
  src/Routes/ImageManagerDetail/ImageDetailTab.js
  src/Routes/ImageManagerDetail/ImageDetailTabs.js
  src/Routes/ImageManagerDetail/ImagePackagesTab.js
  src/Routes/ImageManagerDetail/ImageVersionDetail.js
  src/Routes/ImageManagerDetail/ImageVersionsTab.js
  src/Routes/ImageManagerDetail/__snapshots__/ImageVersionsTab.test.js.snap
  src/Routes/Repositories/Repositories.js
  src/Routes/Repositories/__snapshots__/RepositoryTable.test.js.snap
  src/components/ImageInformationCard.js
  src/components/form/WizardRepositoryTable.js
  src/components/general-table/GeneralTable.js
  src/components/general-table/__snapshots__/GeneralTable.test.js.snap
  src/constants/routeMapper.js
  src/utils/index.js
Labels: documentation, bug fix, ready, new feature, test update
