Repository RedHatInsights/edge-frontend, pull requests merged in 2022-11, with the labels that each got.

#584 Fix async name validation and step navigation in image wizard
  src/Routes/ImageManager/CreateImageWizard.js
  src/Routes/ImageManager/steps/imageSetDetails.js
  src/Routes/ImageManager/steps/index.js
Labels: bug fix, ready

#585 Add cypress tests for large HTTP headers
  cypress/e2e/groups/Groups.cy.js
  cypress/e2e/images/Images.cy.js
  cypress/e2e/repositories/CustomRepositories.cy.js
  cypress/e2e/systems/Systems.cy.js
  cypress/support/commands.js
Labels: ready, test update

#590 Fix broken system detail page
  src/Routes/DeviceDetail/DeviceDetail.js
Labels: bug fix, ready

#586 Clean up custom repo and custom package steps in image wizard
  src/Routes/ImageManager/steps/customPackage.js
  src/components/form/CustomPackageTextArea.js
  src/components/form/WizardRepositoryTable.js
Labels: waiting for review, bug fix, ready

#589 Upgrade redux dependencies
  package-lock.json
  package.json
Labels: bug fix

#591 Update npm dependencies and change package name to edge-frontend
  package-lock.json
  package.json
  src/App.scss
  src/Routes/Groups/GroupTable.js
  src/Routes/Groups/__snapshots__/Groups.test.js.snap
  src/Routes/ImageManagerDetail/DetailsHeader.test.js
  src/Routes/ImageManagerDetail/ImagePackagesTab.test.js
  src/Routes/ImageManagerDetail/__snapshots__/DetailsHeader.test.js.snap
  src/Routes/ImageManagerDetail/__snapshots__/ImagePackagesTab.test.js.snap
  src/Routes/ImageManagerDetail/__snapshots__/ImageVersionsTab.test.js.snap
  src/Routes/Repositories/RepositoryTable.test.js
  src/Routes/Repositories/__snapshots__/RepositoryTable.test.js.snap
  src/Utilities.scss
  src/components/general-table/__snapshots__/FilterChips.test.js.snap
  src/components/general-table/__snapshots__/FilterInput.test.js.snap
  src/components/general-table/__snapshots__/GeneralTable.test.js.snap
  src/components/general-table/__snapshots__/ToolbarFooter.test.js.snap
  src/components/general-table/__snapshots__/ToolbarHeader.test.js.snap
Labels: bug fix, ready

#594 Fix display of button and popover in image wizard custom packages step
  src/Routes/ImageManager/steps/customPackage.js
Labels: waiting for review, bug fix, ready

#593 Remove deprecated frontend-components-inventory-general-info package
  package-lock.json
  package.json
  src/Routes/DeviceDetail/DeviceDetail.js
  src/components/ImageInformationCard.js
Labels: waiting for review, bug fix, ready

#595 Update dependencies
  package-lock.json
  package.json
Labels: bug fix, ready

#598 Fixed image info on device details page
  package-lock.json
  package.json
  src/components/ImageInformationCard.js
Labels: bug fix

#587 THEEDGE-2653 [Crawl] [FE] Enable choose new version when apply an update
  src/Routes/Devices/DeviceTable.js
  src/Routes/Devices/Inventory.js
  src/Routes/Devices/RetryUpdatePopover.js
  src/Routes/Devices/UpdateDeviceModal.js
  src/Routes/Devices/UpdateSystems.js
  src/Routes/Devices/UpdateVersionTable.js
  src/Routes/Groups/__snapshots__/Groups.test.js.snap
  src/Routes/ImageManagerDetail/__snapshots__/ImagePackagesTab.test.js.snap
  src/Routes/ImageManagerDetail/__snapshots__/ImageVersionsTab.test.js.snap
  src/Routes/Repositories/__snapshots__/RepositoryTable.test.js.snap
  src/api/devices/index.js
  src/components/general-table/GeneralTable.js
  src/components/general-table/ToolbarFooter.js
  src/components/general-table/ToolbarHeader.js
  src/components/general-table/__snapshots__/GeneralTable.test.js.snap
  src/components/general-table/__snapshots__/ToolbarFooter.test.js.snap
  src/components/general-table/__snapshots__/ToolbarHeader.test.js.snap
  src/utils/apiWithToast.js
Labels: documentation, new feature

#600 update readme to use nvm
  README.md
Labels: documentation

#597 add support to rhel-87
  src/constants/index.js
Labels: new feature

#558 Added retry popover tests for system details and minor text fix
  .eslintrc.json
  .eslintrc.yml
  cypress/e2e/systems/RetryUpdate.cy.js
  cypress/e2e/systems/SystemDetails.cy.js
  cypress/fixtures/contents.json
  cypress/fixtures/getDevicesId.json
  cypress/fixtures/getDevicesView.json
  cypress/fixtures/getImageSets.json
  cypress/fixtures/getInventoryHosts.json
  cypress/fixtures/getInventoryHostsOperatingSystemVersion.json
  cypress/fixtures/getInventoryHostsSystemProfile.json
  cypress/fixtures/getUpdateDeviceImage.json
  cypress/fixtures/getVulnerabilitySystem.json
  cypress/support/commands.js
  package-lock.json
  package.json
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/Devices/RetryUpdatePopover.js
  src/Routes/ImageManagerDetail/__snapshots__/DetailsHeader.test.js.snap
  src/components/Status.js
Labels: test update

#601 Restore modal when updating multiple systems or from system details page
  src/Routes/Devices/Inventory.js
  src/Routes/Devices/RetryUpdatePopover.js
  src/Routes/Devices/UpdateDeviceModal.js
  src/Routes/Devices/UpdateSystem.js
  src/Routes/Devices/UpdateSystems.js
  src/Routes/Devices/UpdateVersionTable.js
  src/Routes/GroupsDetail/GroupsDetail.js
  src/api/devices/index.js
  src/components/general-table/ToolbarFooter.js
  src/utils/apiWithToast.js
Labels: waiting for review, bug fix, ready

#602 fixing update page overflow
  src/Routes/Devices/UpdateSystem.js
Labels: bug fix, ready, new feature, test update

#605 Remove precommit hook test command
  .husky/pre-commit
Labels: new feature

#603 add rhel-91 support on FE
  package-lock.json
  src/constants/index.js
Labels: new feature

#604 Update dependencies, remove deprecated package
  package-lock.json
  package.json
  src/components/ImageInformationCard.js
Labels: bug fix, ready

#607 Fix multiple renders and modal link display in System Details page
  src/components/DeviceDetail.js
Labels: bug fix, ready

#609 Add RHEL 9.1 to distributionMapper
  src/constants/index.js
Labels: bug fix, ready

#608 Use image-sets view API call in Vulnerability tab
  src/Routes/DeviceDetail/Vulnerability.js
Labels: bug fix, ready

#613 added remaining links for ephemeral
  deploy/frontend.yml
Labels: bug fix
