Repository RedHatInsights/edge-frontend, pull requests merged in 2022-10, with the labels that each got.

#563 Add id to DeviceTable toolbar components
  src/Routes/Devices/DeviceTable.js
  src/components/general-table/ToolbarHeader.js
Labels: bug fix

#560 THEEDGE-2572 - [UI] Add test to cover Groups.js
  cypress/e2e/groups/Groups.cy.js
  cypress/e2e/repositories/CustomRepositories.cy.js
Labels: ready, test update

#564 [Cypress] refactoring sorting tables test
  cypress.config.js
  cypress/e2e/groups/CreateGroupModal.cy.js
  cypress/e2e/groups/Groups.cy.js
  cypress/e2e/images/Images.cy.js
  cypress/e2e/images/UpdateImageWizard.cy.js
  cypress/e2e/repositories/CustomRepositories.cy.js
  cypress/e2e/systems/UpdateSystemsWizard.cy.js
  cypress/support/commands.js
  package-lock.json
  package.json
Labels: bug fix, ready, new feature, test update

#567 Fix prop name in Custom Packages image wizard step
  src/Routes/ImageManager/steps/customPackage.js
Labels: bug fix, ready

#570 THEEDGE-2161
  src/Routes/Repositories/modals/AddModal.js
  src/api/repositories/index.js
Labels: bug fix, ready, new feature, test update

#569 Fix conditional display of Alert by device status in UpdateDeviceModal
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/Devices/DeviceTable.js
Labels: bug fix, ready

#576 Fix async name validation
  src/Routes/Groups/CreateGroupModal.js
  src/Routes/ImageManager/steps/imageSetDetails.js
  src/Routes/Repositories/modals/AddModal.js
  src/components/ImageCreator.js
  src/components/Modal.js
Labels: bug fix

#579 Fixed image create wizard
  package.json
  src/Routes/ImageManager/steps/imageSetDetails.js
  src/components/ImageCreator.js
Labels: bug fix

#581 Add title and appId in quotes
  deploy/frontend.yml
Labels: bug fix
