Repository RedHatInsights/edge-frontend, pull requests merged in 2023-11, with the labels that each got.

#762 Theedge 3581 expose component
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  src/Routes/Devices/DevicesGroupDetail.js
Labels: new feature

#765 add federated command
  README.md
Labels: documentation

#767 THEEDGE-3632: add data validation to show sort option on deviceTable
  src/Routes/Devices/DeviceTable.js
Labels: bug fix

#769 Theedge 3683 fix select all
  src/components/general-table/BulkSelect.js
  src/components/general-table/GeneralTable.js
  src/components/general-table/createFilterValues.js
  src/hooks/useFetchBatched.js
  src/hooks/usePromiseQueue.js
Labels: bug fix

#770 Props to group component
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  src/Routes/Groups/GroupTable.js
  src/Routes/Groups/Groups.js
Labels: new feature

#771 chore: Fix stylelint peer dependency conflict
  package-lock.json
  package.json
Labels: bug fix

#776 fix format
  README.md
Labels: documentation

#777 adding preview prefix when load app
  config/dev.webpack.config.js
  config/prod.webpack.config.js
Labels: bug fix

#778 updates: support inventory group devices update
  src/Routes/Devices/UpdateDeviceModal.js
Labels: new feature

#779 fix group details path
  src/Routes/Groups/GroupTable.js
Labels: bug fix

#781 fix behavior of dropdown
  src/components/general-table/BulkSelect.js
Labels: bug fix

#772 Props to group details component
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  src/Routes/Groups/GroupTable.js
  src/Routes/Groups/Groups.js
  src/Routes/GroupsDetail/GroupsDetail.js
  src/components/general-table/BulkSelect.js
Labels: new feature
