Repository RedHatInsights/edge-frontend, pull requests merged in 2023-07, with the labels that each got.

#703 add mgold to contribute
  .github/CODEOWNERS
Labels: documentation

#697 feat: create new federated module to expose ImageDeatilsCard
  .husky/pre-commit 2
  config/dev.webpack.config.js
  fec.config 2.js
  src/Routes/Devices/DeviceTable.js
  src/components/ImageInformationCard.js
Labels: waiting for review, new feature

#704 fix fedated link to image details
  src/Routes/Devices/DeviceTable.js
Labels: bug fix

#705 chore: Expose ImagesInformationCard thru prod webpack
  config/prod.webpack.config.js
Labels: new feature

#708 fix link behavior to redirect to image-builder federated details
  src/Routes/Devices/DeviceTable.js
Labels: bug fix

#687 THEEDGE-3290 - Match Kebab actions with Insights Kebab
  config/dev.webpack.config.js
  package-lock.json
  package.json
  src/Routes/Devices/DeviceTable.js
  src/Routes/Devices/Inventory.js
  src/api/index.js
  src/store/action-types.js
  src/store/actions.js
  src/utils/index.js
Labels: documentation, new feature

#709 fixing Edit name
  src/store/actions.js
Labels: bug fix

#710 fix validation using hisotyprop
  src/Routes/Devices/DeviceTable.js
Labels: bug fix

#712 fix behavior on back action
  src/components/form/WizardRepositoryTable.js
Labels: bug fix

#718 change the look and feel when there are no images at the screen
  src/App.scss
  src/Routes/ImageManager/ImageSetsTable.js
  src/Routes/ImageManager/__snapshots__/ImageSetsTable.test.js.snap
  src/components/Empty.js
  src/components/__snapshots__/Empty.test.js.snap
Labels: bug fix

#721 add docLinkProp to Images component
  src/Routes/ImageManager/Images.js
Labels: bug fix
