Repository RedHatInsights/edge-frontend, pull requests merged in 2023-08, with the labels that each got.

#722 fixing incorrect Browser Titles for Edge Management pages
  package-lock.json
  package.json
  src/Routes/Devices/Inventory.js
  src/Routes/Groups/Groups.js
  src/Routes/ImageManager/Images.js
  src/Routes/Repositories/RepositoryHeader.js
Labels: bug fix, test update

#724 fix: Aligment on inventory table used as federated module
  src/Routes/Devices/Inventory.js
Labels: bug fix

#725 change notification message on create/update image
  src/Routes/ImageManager/CreateImageWizard.js
  src/Routes/ImageManager/UpdateImageWizard.js
Labels: bug fix

#727 fix:Fix redirect link for custom repositories
  src/Routes/Repositories/RepositoryLinkAccess.js
Labels: bug fix

#726 Theedge 3488
  src/Routes/DeviceDetail/DeviceDetail.js
  src/Routes/Devices/DeviceTable.js
  src/Routes/Devices/Inventory.js
  src/Routes/Devices/UpdateSystem.js
Labels: new feature

#729 fixing custom repos browser title
  src/Routes/Repositories/Repositories.js
  src/Routes/Repositories/RepositoryHeader.js
Labels: bug fix

#728 add notification when edit/delete device
  src/Routes/Devices/Inventory.js
  src/utils/apiWithToast.js
Labels: bug fix

#731 fix parameters when link comes from federation
  src/Routes/Devices/DeviceTable.js
Labels: bug fix
