Repository RedHatInsights/edge-frontend, pull requests merged in 2023-03, with the labels that each got.

#638 THEEDGE-3139 - Add new access to HMS Custom repos screen
  src/Routes/Repositories/Repositories.js
  src/Routes/Repositories/RepositoryLinkAccess.js
Labels: documentation, ready, new feature, test update

#646 remove loop to avoid conflict
  .travis/custom_release.sh
Labels: bug fix

#647 sintaxe fix
  .travis/custom_release.sh
Labels: bug fix

#649 Remove correct dir before running release.sh
  .travis/custom_release.sh
Labels: bug fix

#651 custom-repos: Add uuid field to custom-repos.
  src/api/images/index.js
  src/components/form/WizardRepositoryTable.js
Labels: new feature
