Repository RedHatInsights/edge-frontend, pull requests merged in 2023-01, with the labels that each got.

#624 Remove deprecated insights.chrome.init call
  src/App.js
Labels: bug fix, ready

#625 Add inventory table to our fed-mods
  config/dev.webpack.config.js
Labels: new feature

#626 THEEDGE-2896 - Fix typo on toast notifications while creating images
  src/Routes/ImageManager/CreateImageWizard.js
Labels: bug fix, ready

#627 Add @scalprum/react-core to package.json
  package-lock.json
  package.json
Labels: bug fix, ready

#629 THEEDGE-2923 - Table pagination doesn't work on system update page
  src/Routes/Devices/UpdateSystem.js
  src/Routes/Devices/UpdateVersionTable.js
  src/api/devices/index.js
Labels: documentation, bug fix, ready, new feature, test update

#631 THEEDGE-2230 - adding character limit for repo names
  src/Routes/Devices/UpdateSystem.js
  src/Routes/Repositories/modals/AddModal.js
Labels: documentation, ready, new feature, test update
