Repository RedHatInsights/edge-frontend, pull requests merged in 2024-02, with the labels that each got.

#792 groups: fixes groups error displayed
  src/Routes/Devices/AddDeviceModal.js
  src/Routes/Devices/RemoveDeviceModal.js
  src/Routes/Groups/CreateGroupModal.js
  src/Routes/Groups/Groups.js
  src/Routes/Groups/Groups.test.js
  src/components/SearchInputApi.js
  src/hooks/useInventoryGroups.js
Labels: bug fix, test update

#793 Theedge 3709 add activation key
  src/Routes/ImageManager/CreateImageWizard.js
  src/Routes/ImageManager/UpdateImageWizard.js
  src/Routes/ImageManager/steps/ActivationKeys.js
  src/Routes/ImageManager/steps/imageOutput.js
  src/Routes/ImageManager/steps/index.js
  src/Routes/ImageManager/steps/registration.js
  src/Routes/ImageManagerDetail/ImageDetailTab.js
  src/api/images/index.js
  src/api/index.js
  src/components/ImageCreator.js
  src/components/form/ActivationKeysSelector.js
  src/components/form/ReviewStep.js
  src/store/action-types.js
  src/store/actions.js
Labels: new feature

#794 clean up unused code; add null value to list
  src/components/form/ActivationKeysSelector.js
  src/store/action-types.js
  src/store/actions.js
Labels: new feature

#796 Rename empty group to No Group
  src/Routes/Devices/DeviceTable.js
Labels: bug fix

#797 fix validation for radio on emptyState
  src/Routes/Devices/UpdateSystem.js
Labels: bug fix

#795 device-table: preserve devices filters across pages
  src/Routes/Devices/DeviceTable.js
  src/components/general-table/GeneralTable.js
Labels: bug fix
