Repository RedHatInsights/edge-frontend, pull requests merged in 2025-05, with the labels that each got.

#903 fix: Fix spacing of Image status column
  src/Routes/Devices/RetryUpdatePopover.js
  src/Routes/ImageManagerDetail/__snapshots__/DetailsHeader.test.js.snap
  src/components/Status.js
Labels: waiting for review

#906 Add decommission banner
  src/Routes/Repositories/RepositoryLinkAccess.js
Labels: documentation

#908 HMS-5691 fix missing period after linting
  src/App.js
Labels: bug fix
